runpod/serverless/modules/job.py

Fix the message that's logged so that it says `test_input.json` instead of `test_inputs.json`.

Fix log message for test_inputs.json

---

runpod/endpoint/runner.py

In short
- show server error in error code
- if 429, wait longer between requests
`/{endpoint_id}/status/{job_id}` is not guaranteed to have an "output" key:
```
curl -X POST https://api.runpod.ai/v1/9<redacted>/status/54<redacted> \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer T9<redacted>'
{"delayTime":9862,"error":"name 'app' is not defined","executionTime":97,"id":"54a54b10-d43e-43cb-b29e-c4cac8712ea6","input":{"prompts":["a cute magical flying dog, fantasy art drawn by disney concept artists"]},"status":"FAILED"}
```
In `runpod-python` this results in an uniformative `KeyError`, which is fixed by this PR:
```
File "/usr/src/app/myapp/embeddings/text_embeddings.py", line 60, in send_run_request
return run_request.output()
File …
```

More Informative Errors

---

runpod/serverless/utils/rp_upload.py

As all SD templates use this method in rp_handler, would be nice to natively support boto3 ExtraArgs (like 'CacheControl' and 'ContentType' etc.)  param on upload.

add ExtraArgs support for upload_file_to_bucket

---

runpod/endpoint/runner.py
tests/test_endpoint/test_runner.py

fixes https://github.com/runpod/runpod-python/issues/36#issuecomment-1605511127

Add informative error message when API key not provided

---

runpod/api_wrapper/ctl_commands.py
runpod/api_wrapper/mutations/pods.py

country_code can be passed to create_pod
```python
gpu_count = 1
pod = runpod.create_pod(
name="Test",
image_name="runpod/pytorch:3.10-2.0.1-117-devel",
gpu_type_id="NVIDIA RTX A4000",
cloud_type="COMMUNITY",
country_code="CA",
gpu_count=gpu_count,
volume_in_gb=5,
container_disk_in_gb=5,
ports="8888/http,22/tcp",
)
```

feat: add country_code to create_pod

---

runpod/serverless/modules/rp_ping.py
runpod/serverless/worker.py

Note for future:
The root cause is linked to the creation of TCPConnector() outside of an existing event loop context. TCPConnector establishes its own internal event loop during construction, becoming tightly bound to it. Consequently, when executing the asyncio.ensure_future() function, a separate event loop instance is used to run get_job(). However, this method attempts to use the TCPConnector associated with a different event loop, resulting in a mismatch and leading to the observed error.
To address this issue, the recommended solution involves relocating the line "TCPConnector()" into the body of the run_worker function. This adjustment effectively resolves the problem, preventing the occurrence of the error.

Fixing "timeout context manager should be used inside a task"

---

runpod/serverless/worker.py

This PR updates the detection of HTTP streaming inside the serverless worker by checking if the handler is either an async or non-async function generation handler. In the past, we only detected the non-async function generations, which were insufficient for full support.

Support both async and non-async function generation.

---

runpod/serverless/modules/rp_scale.py

In our job acquisition logic, we need to ensure sequential execution rather than parallel execution, in order to prevent a potential data race within the TakeJob logic in SLS.

Data Race in TakeJob

---

README.md
runpod/__init__.py
runpod/api_wrapper/ctl_commands.py
runpod/api_wrapper/queries/pods.py
tests/test_api_wrapper/test_ctl_commands.py

Hey, I just needed a method to get all my pods and didn't find it in the repo.
Here's my humble implementation.

Add get_pods() API method

---

README.md
runpod/api_wrapper/ctl_commands.py
runpod/api_wrapper/queries/pods.py
tests/test_api_wrapper/test_ctl_commands.py

Just a small method for consistency

Add get_pod() API method

---

runpod/__init__.py
runpod/api_wrapper/queries/pods.py

get_pods() was failing due to double curly brackets in a non-fstring; get_pod(id) simply wasn't imported in __init__

fix for runpod.get_pods() and runpod.get_pod(id)

---

runpod/api/ctl_commands.py
runpod/api/mutations/pods.py
tests/test_api/test_mutations_pods.py

This fixes https://github.com/runpod/runpod-python/issues/145 and https://github.com/runpod/runpod-python/issues/123 by add an optional `template_id` parameter to `createPod()`
I re-ran the unit tests locally via pytest, and everything is passing:
```
pytest
==================================================================================== test session starts =====================================================================================
platform darwin -- Python 3.11.5, pytest-7.4.2, pluggy-1.3.0
rootdir: /Users/tleyden/Development/runpod-python
plugins: anyio-3.7.1
collected 129 items                                                                                                                                                                          
tests/test_whatever.py ... …
```

Support passing a template ID to createPod (#145)

---

runpod/serverless/utils/rp_upload.py

The existing upload code assumes that the user is trying to upload an image, and forces the S3 content type to PNG regardless of what the file actually is.
This version first tries an image-based approach, setting the content type by the image type, and then falls back to a file-based upload. 
Any exceptions caused by anything other than PIL detecting it's not an image will still be handled in the remainder of the code.

Added code to handle non-image uploads in runpod.serverless.utils.rp_upload.files(...)

---

requirements.txt

In order to resolve multiple security vulnerabilities in aiohttp releases prior to 3.9.5, relax the dependency requirement so that 3.9.5 is an allowed version.

Allow newer aiohttp versions

---

examples/serverless/concurrent_handler.py
runpod/serverless/__init__.py
runpod/serverless/modules/rp_scale.py
runpod/serverless/worker.py
tests/test_serverless/test_worker.py

This was an unnecessary premature optimization that caused DDoS on our platform.
TODO: Refactor for proper job scheduling algorithm using asyncio.Queue

Deprecated JobScaler.concurrency_modifier

---

.pylintrc

Add @deanq 's `.pylintrc`. We should choose to merge _exactly one_ of https://github.com/runpod/runpod-python/pull/343 and https://github.com/runpod/runpod-python/pull/346

fix: less persnickety .pylintrc

---

pytest.ini

Not all lines will be covered all the time, this is normal. Setting
numbers that are too strict encourages chasing metrics rather than
reasonable test coverage.

Use less strict numbers for coverage.

---

runpod/__init__.py
runpod/api/ctl_commands.py
runpod/api/mutations/container_register_auth.py
tests/test_api/test_mutation_container_registry_auth.py

adds wrappers for:
* UpdateRegistryAuth (runpod.update_container_registry_auth)
* DeleteRegistryAuth (runpod.delete_container_registry_auth)
and tests similar to what exists for generate_container_registry_auth
should address #317 
tried it on my account, seems to work

add wrappers for UpdateRegistryAuth and UpdateRegistryAuth.

---

.github/workflows/CI-pytests.yml
.gitignore
examples/serverless/concurrent_handler.py
runpod/serverless/modules/rp_fastapi.py
runpod/serverless/modules/rp_http.py
runpod/serverless/modules/rp_job.py
runpod/serverless/modules/rp_logger.py
runpod/serverless/modules/rp_ping.py
runpod/serverless/modules/rp_scale.py
runpod/serverless/modules/worker_state.py
runpod/serverless/worker.py
tests/test_serverless/test_modules/test_http.py
tests/test_serverless/test_modules/test_job.py
tests/test_serverless/test_modules/test_ping.py
tests/test_serverless/test_modules/test_state.py
tests/test_serverless/test_worker.py

- Restored concurrency_modifier support
- Concurrent calls now use batched job takes instead of multiple parallel singular job takes
- Using asyncio.Queue to track jobs queue and processing
- JobScaler refactored to properly coordinate job takes and processing

Batch Concurrency

---

runpod/serverless/modules/rp_fastapi.py
runpod/serverless/modules/rp_job.py
runpod/serverless/modules/rp_ping.py
runpod/serverless/modules/rp_scale.py
runpod/serverless/modules/worker_state.py
runpod/serverless/worker.py
tests/test_serverless/test_modules/test_ping.py
tests/test_serverless/test_modules/test_state.py
tests/test_serverless/test_worker.py

- Distinguish JobsQueue(asyncio.Queue) and JobsProgress(set) and reference them appropriately
- Cleaned up JobScaler.process_job --> rp_job.handle_job
- Graceful cleanup when worker is killed
- More tests

fix: pings were missing requestIds since the last big refactor

---

runpod/serverless/core.py

This only effects the serverless core code path, so it should be safe.

fix: `sls-core` not reporting status code 2

---

runpod/serverless/modules/rp_job.py
runpod/serverless/modules/rp_scale.py
runpod/serverless/modules/worker_state.py
runpod/serverless/worker.py
runpod/tracer.py
tests/test_serverless/test_modules/test_job.py
tests/test_serverless/test_worker.py

Fix: This was causing unnecessary delays in serverless workers.
- Refactored rp_job.get_job to work well under pause and unpause conditions. More debug lines too.
- Refactored rp_scale.JobScaler to handle shutdowns where it cleans up hanging tasks and connections gracefully. Better debug lines.
- Fixed rp_scale.JobScaler from unnecessary long asyncio.sleeps made before considering the blocking get_job calls.
- Improved worker_state's JobProgress and JobsQueue to timestamp when jobs are added or removed.
- Incorporated the lines of code in worker.run_worker into rp_scale.JobScaler where it belongs and simplified to `job_scaler.start()`
- Fixed non-error logged as errors in tracer
- Updated unit tests mandating these changes

Blocking job take call means 5-sec debounce no longer needed

---

runpod/serverless/modules/rp_scale.py

The bug was caused by an asyncio event loop locking up. Adding `finally: await asyncio.sleep(0)` fixed it.
This fixes issues like https://github.com/runpod/runpod-python/issues/368 and other similar reported issues.

fix: long-running jobs crash with SIGTERM

---

runpod/api/ctl_commands.py
runpod/api/mutations/pods.py

community pods can have slow network speeds
this PR adds support for the 2 graphQL parameters "minDownload" and "minUpload" to runpod.create_pod

minimum network speed parameters for create_pod

---

runpod/serverless/utils/rp_validator.py
tests/test_serverless/test_utils/test_validate.py

This pull request includes changes to the input validation logic for issue #373 and the corresponding unit tests.

Fixes issue #373 for required input validation

---

runpod/serverless/modules/rp_job.py

This created false-positive completed tasks

fix: streamed errors were previously swallowed

---

runpod/serverless/__init__.py
runpod/serverless/modules/rp_scale.py
tests/test_serverless/test_modules/test_scale.py
tests/test_serverless/test_worker.py

All other SDK functions should not be affected

Fix: handle uncaught exception only for Serverless workers

---

runpod/serverless/modules/rp_scale.py

Users are concerned by the ‘kill worker’ log message. Move it under `debug` instead of `info`, as it’s just the system signaling the container to terminate.

fix: change log to debug

---

runpod/api/graphql.py

No longer recommending the query param method

Update: GQL uses API Key in Authorization Header

---

runpod/endpoint/asyncio/asyncio_runner.py
tests/test_endpoint/test_asyncio_runner.py

The async job's streaming method runs indefinitely without specifically calling a break outside of the function. 
This change handles the break when the job is complete AND all the stream data has been consumed. (The stop condition should check for the `{status: "COMPLETED", stream: []}` job response.
This is in sync with the runner stream implementation. The test case has also been updated.

Update async job streaming stop condition and test cases

---

runpod/serverless/utils/rp_validator.py

fix: skip type check for default values in validation

---

runpod/serverless/modules/rp_scale.py

Just catch the `asyncio.TimeoutError` and throw in a debug log for it.

fix: better exception handling.

---

README.md
runpod/api/ctl_commands.py
runpod/api/mutations/pods.py
tests/test_api/test_mutations_pods.py

This PR introduces a basic implementation for creating pods using the Python SDK. Previously, there was no direct support for this, as noted in [issue #314](https://github.com/runpod/runpod-python/issues/314). I integrated a minimal version of pod creation and added a unit test to validate its functionality.
- Implemented pod creation method in the SDK.
- Added a unit test to verify pod creation.
- Updated the README with instructions on how to create a pod from Python.
I tested the implementation with the following example:
```python
import runpod
print("Creating CPU pod...")
pod = runpod.create_pod(
name="test-cpu-pod",
instance_id="cpu3c-2-4",
template_id="runpod-ubuntu",
)
print(f"CPU Pod created with ID: {pod['id']}")
```
The output confirmed successful pod creation:
```
Creating CPU …
```

Add CPU Pod Creation Support in Python SDK

---

runpod/api/ctl_commands.py
runpod/api/mutations/endpoints.py

This corrects some of the changes from https://github.com/runpod/runpod-python/pull/375
This keeps it consistent with our graphql specs.

fix: allowed_cuda_versions was incorrectly typed as string

---

runpod/serverless/utils/rp_download.py
tests/test_serverless/test_utils/test_download.py

fix: parse Content-Disposition properly, closes #414

---

runpod/cli/groups/pod/commands.py
runpod/serverless/utils/rp_debugger.py
tests/test_cli/test_cli_groups/test_pod_commands.py
tests/test_serverless/test_utils/test_download.py

`croc` is not a good enough solution, it is often extremely slow since RunPod is using our own middle-man servers.
This is an option to help mitigate the issue so that if people are using RunPod official pod templates, and have the proper public keys configured, they can sync the data.
Worst happens, they can pause the pod, add the key, and then move on. This is at the very least a very easy way to sync data across to a new pod when someone gets spun up with zero GPUs.
Added unit tests
Manual testing
```
runpod-python % runpod pod sync ygyprlkeddwn6c 5e03t4xc9epwle
✅ Found 5 SSH key(s) in your account
🔄 Syncing from ygyprlkeddwn6c:/workspace to 5e03t4xc9epwle:/workspace
📡 Connecting to source pod ygyprlkeddwn6c...
Connected to pod 213.173.99.7:24135 using key Runpod-Key2
📊 Counting files …
```

feat: Adding a sync function to runpod-python sdk to help copying workspace between pods

---

docs/serverless/worker.md
docs/serverless/worker_realtime.md
runpod/endpoint/asyncio/asyncio_runner.py
runpod/error.py
tests/test_serverless/__init__.py
tests/test_serverless/test_modules/test_logger.py

Hi,
Found some typos when reading the docs in detail.
Trying to fix them with this PR.
Regards,
Didier

[Doc]: fixing some typos

---

.github/workflows/CI-e2e.yml

Hi,
This job currently fails on fork due to missing access to secrets.
Adding the ìf`condition with repo prevent the job from running (hence the failure) on forks.
Best,
Didier

[fix]: prevent CI job run failures on fork
